// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsrVIIzhgWYCndbOXj_IbS5zCg6XOvCKA',
    appId: '1:723628554574:web:312d29b3f35e23b01f061f',
    messagingSenderId: '723628554574',
    projectId: 'adv-exam-7a91f',
    authDomain: 'adv-exam-7a91f.firebaseapp.com',
    storageBucket: 'adv-exam-7a91f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTijCZrDoEuibRZrK7PLJXwBwZWKTqTZ4',
    appId: '1:723628554574:android:f1eb75ff258d879f1f061f',
    messagingSenderId: '723628554574',
    projectId: 'adv-exam-7a91f',
    storageBucket: 'adv-exam-7a91f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5XvJXDFpH8uKGgoG_GuMg-xZAPSBJkh0',
    appId: '1:723628554574:ios:b9133d0292045dab1f061f',
    messagingSenderId: '723628554574',
    projectId: 'adv-exam-7a91f',
    storageBucket: 'adv-exam-7a91f.appspot.com',
    iosBundleId: 'com.example.advExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5XvJXDFpH8uKGgoG_GuMg-xZAPSBJkh0',
    appId: '1:723628554574:ios:b9133d0292045dab1f061f',
    messagingSenderId: '723628554574',
    projectId: 'adv-exam-7a91f',
    storageBucket: 'adv-exam-7a91f.appspot.com',
    iosBundleId: 'com.example.advExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsrVIIzhgWYCndbOXj_IbS5zCg6XOvCKA',
    appId: '1:723628554574:web:a27cb040e8ba62e41f061f',
    messagingSenderId: '723628554574',
    projectId: 'adv-exam-7a91f',
    authDomain: 'adv-exam-7a91f.firebaseapp.com',
    storageBucket: 'adv-exam-7a91f.appspot.com',
  );
}
